name: coupon_app
description: Get a coffee coupon
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.5+1
  http: ^1.6.0
  dio: ^5.9.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  html: ^0.15.6
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  intl: ^0.20.2
  email_validator: ^3.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true
  color: "#FCF8F2"
  image: assets/main_screen_icon.png
  android_12:
    color: "#FCF8F2"
    image: assets/main_screen_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/main_screen_icon.png
    - assets/app_icon_white.png
    - assets/app_icon_no_background.png
